### ISSUE TITLE
Add support for the rest of Gany's Mods

### ISSUE THREAD

**Issue by T145** [ganymedes01/Et-Futurum#63]
Rather than having to enable and disable everything manually, it would be nice if this mod supported the rest of the Gany's Mods, so it's less of a hassle for a user. Better yet, the features that overlap can all just be put into this mod, rather than having similar content across multiple mods.

**Comment by buttilda** [comment]
The overlapping features are automatically turned off in Gany's Surface. You either have an old version, or didn't reset the config file ever since the update that added that convinience came out.

As for moving things to this mod... no way. Et Futurum is dedicated to only backporting features. I'm not adding my own

Removing the overlapping stuff from Gany's Surface would break existing worlds, otherwise I'd have done it by now. Believe me, it annoys me just as much as it annoys you XD
