### ISSUE TITLE
Daylight sensor code messes with Witchery's sunlight collector

### ISSUE THREAD

**Issue by darthvader45** [ganymedes01/Et-Futurum#99]
@EzerArch Apparently this mod's invertable daylight sensor feature messes with the vanilla daylight sensor in 1.7.10, causing the sun collectors from Witchery to not work.  Seems it makes the daylight sensor to not be recognized as such.

**Comment by DarianLStephens** [comment]
Actually, this totally replaces the block.
It still exists, this mod just replaces it with its own version every chance it gets.
You can just turn off the daylight sensor feature in this mod, though; It's easy enough to invert the signal yourself.

**Comment by darthvader45** [comment]
Maybe adding compat would work?

Golden rule in Minecraft: Never dig straight down.

**Comment by EzerArch** [comment]
@darthvader45, I'm not the maintainer of this mod. It's @ganymedes01, but he hasn't been working on the mod since January.

**Comment by DarianLStephens** [comment]
You should talk to @KryptonCaptain, since they're continuing a branch of this mod.

**Comment by EzerArch** [comment]
Thanks. :)

For those who want to find the releases: https://github.com/KryptonCaptain/Et-Futurum/releases _(Note: I haven't tried them yet)_

EDIT: the changes so far: https://github.com/KryptonCaptain/Et-Futurum/commits/krypt

EDIT2: it seems he desperately needs coding help: https://github.com/KryptonCaptain/Et-Futurum/commit/3ef6cdc2f99f78c9757faee2e5a79b3809987586 :3

**Comment by darthvader45** [comment]
Sounds awesome.  Wonder if guardians are still impossible?  @KryptonCaptain

Golden rule in Minecraft: Never dig straight down.

**Comment by KryptonCaptain** [comment]
An attempt was made. It was then abandoned, because I truly do not understand AI code for mobs

**Comment by darthvader45** [comment]
It's okay to get help on that.  I'm sure someone on the forums can help.

**Comment by DarianLStephens** [comment]
@KryptonCaptain 
Just so you know, your efforts were not in vain; AstroTibs learned from your attempt and finally managed to port Guardians to 1.7.10 in version 3.0 of his 'Village Names' mod.

**Comment by ghost** [comment]
i think you can just disable the item completely from settings

**Comment by DarianLStephens** [comment]
Yeah, you can turn the daylight sensor off. You can also just use the conversion recipe (Put the sensor in the crafting grid to switch between vanilla and Et Futurum), which allows you to keep the benefits of the new one while having the old for things that need it.

**Comment by darthvader45** [comment]
Oh, cool.  Will remember that.

**Comment by DarianLStephens** [comment]
The only thing is you have to keep track of which version of Daylight Sensor you've got. Right-clicking it while it's placed in the world will tell you which it is. Vanilla (Witchery-compatible) will do nothing, while the Et Futurum one will switch to night mode (And turn blue).

**Comment by ghost** [comment]
Also in KryptonCaptain's build you can disable entity replacements to maximize compatibility (which disables all blocks that depend on this including this one if im not mistaken). I am actually working on Witchery code atm  maybe i can look into that

**Comment by darthvader45** [comment]
Really?  Cool.  If you ever decide to do a 1.12.2 port to compete with the spiritual successors Bewitchment and Covens, I'd be happy to help.

**Comment by ghost** [comment]
@darthvader45  I'm not doing any ports. 1.7.10 forever. Plus this whole thing works for me because in my country we have  special orphan works license allows me to circumvent some of the copyright provided work is completely abandoned.

**Comment by DarianLStephens** [comment]
Huh. Well, if you're looking in to it, perhaps you could see if the teleportation code is using forge standards? I've noticed that Witchery teleportation, and only Witchery's, seems to cause some desync or plain weirdness, particularly losing your experience bar client-side when travelling between dimensions, and some entities at the destination becoming un-interactable.
I suspect that Witchery is using some outdated methods or missing some data which should be relatively simple to fix.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
so here is your issue 
![image](https://user-images.githubusercontent.com/36826319/65211239-05caa300-da6c-11e9-9937-ed6a0c074d76.png)

Witchery specifically checks for adjacent Blocks.daylight_detector . Since this mod replaces the daylight detector with a custom block the easy fix would be to change witchery code to instanceof instead. The only other fix I can think of is completely disable the block. The really hard fix is to implement the block using ASM which is doable but I have no idea how to asm. You would have to reflect the class loop though variables and check specific bytecotes and change data before jit.

**Comment by ghost** [comment]
so here is your issue  in witchery code
![image](https://user-images.githubusercontent.com/36826319/65211437-af119900-da6c-11e9-8f78-61b5c179163d.png)


Witchery specifically checks for adjacent Blocks.daylight_detector . Since this mod replaces the daylight detector with a custom block the easy fix would be to change witchery code to instanceof instead. 

The getblock must also be changed to get any block that's adjacent and check for instanceof then cast that to a daylight sensor block since the Et Futurum block extends daylight sensor it will work.

The only other fix and easiest I can think of is completely disable the block. 

The really hard fix is to implement the block using ASM in etfuturum which is doable but I have no idea how to asm works. Also if you're completely changing the block is gonna be pretty difficult.

**Comment by ghost** [comment]
https://github.com/ganymedes01/Et-Futurum/blob/master/src/main/java/ganymedes01/etfuturum/blocks/NewDaylightSensor.java

Further inspection it appears etfuturum changes the block itself but not the item. I think it's using the new block replacement feature that was added in later versions of forge. 

You would have to investigate this but I think the changes are very minimal so it may be possible to implement this using asm.

**Comment by DarianLStephens** [comment]
I wonder if you could do away with that sensor block completely and just detect right-clicks on the original daylight sensor for replacement with the inverted one? That would solve the compatibility issues, and it makes sense that you couldn't gather sunlight from a sensor in moon mode.

**Comment by ghost** [comment]
when you right click on the daylight sensor it becomes inverted daylight sensor. The block is completely replace ONLY to turn it into an inverted one when you activate it. You could probably use events instead of replacing the block completely.   subscribe to a when player uses block

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
So the easiest fix I can think of is simply to comment out the field NewDaylightSensor from ModsBlocks. Then in the core/handlers  event handler class add a new event subscription to PlayerInteractEvent.useBlock . In there you wanna check if the block is Blocks.daylightSensor (vanilla one) and if so then replace that block with InvertedDailightSensor. You must also modify the inverted daylightsensor to extend the regular DailightSensor and move all the NewDailightSensor Activate functions (i blieve is 2 ofthem) to InvertedDaylightSensor. This will replace the block on an event keeping the original block intact and maximizing compatibility.

**Comment by ghost** [comment]
So the easiest fix I can think of is simply to get rid of the block replacement and use events for adding activation to the vanilla sensor. 

- Comment out the field NewDaylightSensor from ModBlocks. 
- In the core/handlers  event handler class add a new event subscription to PlayerInteractEvent.useBlock . In there you wanna check if the block is Blocks.daylightSensor (vanilla one) AND is interact is e.actio﻿n == PlayerInteractEvent.Action.RIGHT_CLICK﻿_BL﻿OC﻿K and if so then replace that block with InvertedDailightSensor block from this mod. 
- Modify the InvertedDaylightSensor to extend the regular DaylightSensor and also move all the NewDaylightSensor Activate functions (i blieve is 2 ofthem) to InvertedDaylightSensor.

 

This will replace the block on an event keeping the original block intact and maximizing compatibility.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Ill try to patch this on my github when I get home see if my idea works.

**Comment by darthvader45** [comment]
Sounds cool. Yo, Carl, if you actually manage to port Witchery to 1.12.2 or even 1.13.2, I'd be over the moon.  You don't have to though, do what you want.

**Comment by ghost** [comment]
@darthvader45  haha you asked me before and i said im not doing it 😊. 1. im not the owner of the mod i'm mostly fooling around with the code for personal use 2. i dont like new version of mc. i only play 1.7.10 and usually backport features i like to older mc 3. some of the things that witchery does are not possible in newer minecrafts because of core changes 4. it would require incredible amount of work because new mc past 1.8 works with models and blockstates . pretty much ALL blocks and 3d models will have to be re-created using json models and blockstates. creating 1 model alone takes 1 day to 1 week imagine having to recreate everything. im not doing it not ever. haha sorry dude. i estimate it should take 1-3 years for  one person to port this mod. is easier to re-create it

**Comment by ghost** [comment]
@darthvader45  update. There is in fact an unofficial Witchery port for 1.12. There is a whole team of people that have been working to port the original Witchery codebase  to newer minecraft. The problem is due to licensing the port remains under the radar and cannot be posted anywhere. The code is also closed source so all you get is their binaries which they released on their discord. You would need to find their Discord link.

**Comment by darthvader45** [comment]
It's going to be using completely unique assets to avoid violating the license, and as such will eventually make it onto Curseforge or something similar.  I'm on the Discord regularly.

**Comment by DarianLStephens** [comment]
Would it be possible to give some sort of clue to finding this?
I've been doing some hunting, but the closest I feel I've gotten is a deleted reddit post with no record on The Wayback Machine.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@DarianLStephens  I was in the group but I left because I don't play any mods past 1.7.10. I actually tried the mod and it crashed numerous times but is really cool. They are adding a whole bunch of additional models and changes while keeping the mod intact. Is 1000 times better than Bewitchment. You would need to find someone that is in the group to add you.

**Comment by ghost** [comment]
@DarianLStephens  I know all the info but I won't post it here. Post your discord handle and enable receive messages from everyone and someone will reach out to you.

**Comment by DarianLStephens** [comment]
Hopefully this is the right info: Darian Stephens#6835
I _should_ be able to receive messages from anyone, but I'm not sure; they might need to send a friend request first.
